[build]
  publish = "public"
  functions = "netlify/functions"

[context.production.environment]
  SUPABASE_URL = "https://votre-id-supabase.supabase.co"
  SUPABASE_KEY = "votre-cle-api-supabase"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"